# Generated by Django 3.1.7 on 2021-07-16 03:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libros', '0002_auto_20210715_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaLibros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fec_reserva', models.DateTimeField(default=django.utils.timezone.now)),
                ('fec_expiracion', models.DateTimeField(default=datetime.datetime(2021, 7, 17, 3, 39, 1, 797204, tzinfo=utc))),
                ('estado', models.BooleanField(default=True)),
                ('cantidad', models.IntegerField(default=1)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.libro')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserva.reserva')),
            ],
            options={
                'ordering': ['-fec_reserva'],
            },
        ),
        migrations.AddField(
            model_name='reserva',
            name='libros',
            field=models.ManyToManyField(through='reserva.ReservaLibros', to='libros.Libro'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
