# Generated by Django 3.1.7 on 2021-07-16 14:18

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservalibros',
            name='cantidad',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='reservalibros',
            name='fec_expiracion',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 17, 14, 18, 54, 488553, tzinfo=utc)),
        ),
    ]
