# Generated by Django 3.1.7 on 2021-07-16 14:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0002_auto_20210716_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservalibros',
            name='cantidad',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=1),
        ),
        migrations.AlterField(
            model_name='reservalibros',
            name='fec_expiracion',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 17, 14, 30, 22, 732373, tzinfo=utc)),
        ),
    ]
