# Generated by Django 3.1.7 on 2021-06-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0002_auto_20210603_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservalibros',
            name='fec_reserva',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
