# Generated by Django 3.1.7 on 2021-06-03 22:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0003_auto_20210603_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservalibros',
            name='fec_reserva',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
