# Generated by Django 3.1.7 on 2021-07-16 15:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import reserva.models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0004_auto_20210716_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservalibros',
            name='cantidad',
            field=models.IntegerField(default=reserva.models.get_cant_max_reserva),
        ),
        migrations.AlterField(
            model_name='reservalibros',
            name='fec_expiracion',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 17, 15, 1, 56, 179339, tzinfo=utc)),
        ),
    ]
