# Generated by Django 3.1.7 on 2021-07-16 15:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import reserva.models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0005_auto_20210716_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservalibros',
            name='cantidad',
            field=models.IntegerField(default=reserva.models.cantidad_maxima_reserva),
        ),
        migrations.AlterField(
            model_name='reservalibros',
            name='fec_expiracion',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 17, 15, 2, 38, 210199, tzinfo=utc)),
        ),
    ]
