# Generated by Django 3.1.7 on 2021-07-01 02:56

from django.db import migrations, models
import metodos_pago.models


class Migration(migrations.Migration):

    dependencies = [
        ('metodos_pago', '0002_auto_20210630_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjeta',
            name='tipo',
            field=models.CharField(choices=[(metodos_pago.models.TipoTarjeta['DEBITO'], 'DEBITO'), (metodos_pago.models.TipoTarjeta['CREDITO'], 'CREDITO')], default=metodos_pago.models.TipoTarjeta['CREDITO'], max_length=20),
        ),
    ]
