# Generated by Django 3.1.7 on 2021-07-15 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fantasia', models.BooleanField(verbose_name=False)),
                ('ciencia_ficcion', models.BooleanField(verbose_name=False)),
                ('terror', models.BooleanField(verbose_name=False)),
                ('romance', models.BooleanField(verbose_name=False)),
                ('mitología', models.BooleanField(verbose_name=False)),
                ('policial', models.BooleanField(verbose_name=False)),
                ('drama', models.BooleanField(verbose_name=False)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('issn', models.CharField(max_length=9, unique=True)),
                ('titulo', models.CharField(max_length=110)),
                ('autor', models.CharField(max_length=50)),
                ('editorial', models.CharField(max_length=50)),
                ('fec_publicacion', models.DateField()),
                ('estado', models.CharField(choices=[('Nuevo', 'Nuevo'), ('Usado', 'Usado')], default='Nuevo', max_length=50)),
                ('existencias', models.IntegerField()),
                ('idioma', models.CharField(choices=[('Español', 'Español'), ('Ingles', 'Ingles'), ('Ruso', 'Ruso'), ('Japones', 'Japones'), ('Coreano', 'Coreano')], default='Español', max_length=50)),
                ('num_pags', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('portada', models.ImageField(upload_to='libros/portadas')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('genero', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='libros.genero')),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.libro')),
            ],
        ),
    ]
