# Generated by Django 3.1.7 on 2021-07-06 20:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_auto_20210625_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='creado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libros.libro')),
            ],
        ),
    ]
