# Generated by Django 3.1.7 on 2021-06-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('valor', models.IntegerField(null=True)),
                ('estado', models.BooleanField(null=True)),
                ('libros', models.ManyToManyField(null=True, to='libros.Libro')),
            ],
        ),
    ]
