# Generated by Django 3.1.7 on 2021-05-23 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='estado',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='libros',
            field=models.ManyToManyField(null=True, to='libros.Libro'),
        ),
        migrations.AlterField(
            model_name='carrito',
            name='valor',
            field=models.IntegerField(null=True),
        ),
    ]
