# Generated by Django 3.1.7 on 2021-06-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_auto_20210625_1653'),
        ('carrito', '0003_carritocompras_carritolibros'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritocompras',
            name='libros',
            field=models.ManyToManyField(through='carrito.CarritoLibros', to='libros.Libro'),
        ),
    ]
