# Generated by Django 3.1.7 on 2021-06-26 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0004_carritocompras_libros'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carritolibros',
            old_name='libros',
            new_name='libro',
        ),
    ]
