# Generated by Django 3.1.7 on 2021-06-29 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0005_auto_20210626_1723'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrito',
        ),
    ]
