# Generated by Django 3.1.7 on 2021-04-22 03:16

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('genero', models.CharField(choices=[('M', 'masculino'), ('F', 'femenino'), ('O', 'otro')], default='O', max_length=20)),
                ('direccion', models.CharField(max_length=50)),
                ('lugar_nac', models.CharField(max_length=20)),
                ('fecha_nac', models.DateField()),
                ('foto', models.ImageField(upload_to='usuarios/fotos')),
                ('DNI', models.IntegerField()),
                ('preferencias', models.CharField(choices=[('terror', 'terror'), ('drama', 'drama'), ('ficcion', 'ficcion')], default='terror', max_length=20)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
