# Generated by Django 3.1.7 on 2021-04-25 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('DNI', models.IntegerField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(blank=True, max_length=50)),
                ('apellidos', models.CharField(blank=True, max_length=50)),
                ('direccion', models.CharField(blank=True, max_length=50)),
                ('lugar_nac', models.CharField(blank=True, max_length=20)),
                ('fecha_nac', models.DateField(null=True)),
                ('genero', models.CharField(choices=[('M', 'masculino'), ('F', 'femenino'), ('O', 'otro')], default='O', max_length=20)),
                ('foto', models.ImageField(blank=True, upload_to='usuarios/fotos')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
