# Generated by Django 3.1.7 on 2021-07-14 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20210625_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(upload_to='usuarios/fotos'),
        ),
    ]
