# Generated by Django 3.1.7 on 2021-05-28 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20210527_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preferencia',
            name='usuario',
        ),
        migrations.AddField(
            model_name='preferencia',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
