# Generated by Django 3.1.7 on 2021-05-28 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20210528_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferencia',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.perfil'),
        ),
    ]
