# Generated by Django 3.1.7 on 2021-05-31 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20210528_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferencia',
            name='preferencia',
            field=models.CharField(max_length=20),
        ),
    ]
