# Generated by Django 3.1.7 on 2021-06-01 03:39

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_auto_20210531_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferencia',
            name='preferencia',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('terror', 'terror'), ('drama', 'drama'), ('ficcion', 'ficcion')], max_length=20),
        ),
    ]
