# Generated by Django 3.1.7 on 2021-06-01 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_auto_20210531_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferencia',
            name='preferencia',
            field=models.CharField(choices=[('terror', 'terror'), ('drama', 'drama'), ('ficcion', 'ficcion')], default='terror', max_length=20),
        ),
    ]
