# Generated by Django 3.1.7 on 2021-06-27 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ordenes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carrito', '0005_auto_20210626_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[(ordenes.models.OrdenEstado['CREADO'], 'CREADO'), (ordenes.models.OrdenEstado['PAGADO'], 'PAGADO'), (ordenes.models.OrdenEstado['COMPLETADO'], 'COMPLETADO'), (ordenes.models.OrdenEstado['CANCELADO'], 'CANCELADO')], default=ordenes.models.OrdenEstado['CREADO'], max_length=50)),
                ('total_envio', models.DecimalField(decimal_places=2, default=5, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrito.carritocompras')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
