# Generated by Django 3.1.7 on 2021-07-16 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ordenes.common


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('envios', '0001_initial'),
        ('metodos_pago', '0001_initial'),
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_id', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(choices=[(ordenes.common.OrdenEstado['CREADO'], 'CREADO'), (ordenes.common.OrdenEstado['PAGADO'], 'PAGADO'), (ordenes.common.OrdenEstado['COMPLETADO'], 'COMPLETADO'), (ordenes.common.OrdenEstado['CANCELADO'], 'CANCELADO')], default=ordenes.common.OrdenEstado['CREADO'], max_length=50)),
                ('total_envio', models.DecimalField(decimal_places=2, default=5, max_digits=8)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrito.carritocompras')),
                ('direccion_envio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='envios.direccionenvio')),
                ('metodo_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metodos_pago.tarjeta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
