# Generated by Django 3.1.7 on 2021-06-28 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0001_initial'),
        ('ordenes', '0002_orden_orden_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='direccion_envio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='envios.direccionenvio'),
        ),
    ]
