# Generated by Django 3.1.7 on 2021-07-02 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metodos_pago', '0003_auto_20210630_2156'),
        ('ordenes', '0003_orden_direccion_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='metodo_pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='metodos_pago.tarjeta'),
        ),
    ]
